version: "3"
services:
  tests:
    build: .
    environment:
      TF_VAR_sts_endpoint: http://mocksts:5000/
    volumes:
      - ${PWD}:/var/run/code/
    working_dir: "/var/run/code/"
    depends_on:
      - mocksts
    command: ["go", "test", "-v"]
  mocksts:
    image: mergermarket/motoserver
    command: ["sts", "-H", "0.0.0.0", "-p", "5000"]
